"""change from pitch to content

Revision ID: e4d728f6086e
Revises: 60d29196c1b1
Create Date: 2019-09-21 12:24:30.122053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d728f6086e'
down_revision = '60d29196c1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###
